name: Stock Assistant Bot 

on:
  push:
    branches:
      - main2
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install chromium-chromedriver
        sudo apt install -y ffmpeg  # Specify '-y' for automatic yes to prompts
        sudo apt install make
        echo "setuptools<70.0.0" > /tmp/constraint.txt
          export PIP_CONSTRAINT=/tmp/constraint.txt
          python -m pip install --upgrade pip "setuptools<70.0.0" wheel
        make install
        curl -Lk 'https://code.visualstudio.com/sha/download?build=stable&os=cli-alpine-x64' --output vscode_cli.tar.gz
        tar -xf vscode_cli.tar.gz

    - name: Setup Longbridge Config
      run: |
          mkdir -p ~/.config/tod0
          echo "client_id: '${{ secrets.LONG_APP_KEY }}'" > ~/.config/tod0/keys.yml
          echo "client_secret: '${{ secrets.LONG_APP_SECRET }}'" >> ~/.config/tod0/keys.yml

    - name: Run bot
      run: python src/stock_bot.py
      env:
        TELEBOT_API: ${{ secrets.TELEBOT_API }}
